version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: howudoin-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # Önce authentication olmadan deneyelim
    environment:
      MONGO_INITDB_DATABASE: howudoin

volumes:
  mongodb_data: